spring:
    datasource:
        username: postgres
        password: admin202
        url: jdbc:postgresql://localhost:5432/bookDb
    jpa:
        defer-datasource-initialization: true
        hibernate:
            ddl-auto: update
        show-sql: true
    sql:
        init:
            mode: always
            data-locations: classpath:appdata.sql

security:
    jwt:
        sign-key: "9z$C&F)H@McQfTjWnZr4u7x!A%D*G-Ka"
